#!/bin/bash

# Variables {

# Editor
export VISUAL='emacsclient'
export ALTERNATE_EDITOR='emacs -Q -nw'
# }

# Locale {
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# }

# Path {

if [ -d "$HOME/.bin" ]; then
    export PATH="$HOME/.bin:$PATH"
fi

# Homebrew
HOMEBREW_MIRROR='ustc'

if [ "$HOMEBREW_MIRROR" = 'ustc' ]; then
    # https://mirrors.ustc.edu.cn/help/brew.git.html
    export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
    # https://mirrors.ustc.edu.cn/help/homebrew-core.git.html
    export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
    # https://mirrors.ustc.edu.cn/help/homebrew-bottles.html
    export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles

elif [ "$HOMEBREW_MIRROR" = 'tuna' ]; then
    # https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
    export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
    export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
    # https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/
    export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
fi

export HOMEBREW_NO_ANALYTICS=1

if [[ -d "$HOME/homebrew" ]]; then
    export PATH=$HOME/homebrew/bin:$PATH
    export LD_LIBRARY_PATH=$HOME/homebrew/lib:$LD_LIBRARY_PATH
    export CMAKE_PREFIX_PATH=$HOME/homebrew:$CMAKE_PREFIX_PATH
fi

# Rust
RUST_MIRROR='ustc'

#export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export PATH=$PATH:$HOME/.cargo/bin

if [ "$RUST_MIRROR" = 'ustc' ]; then
  export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
  export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup
  # https://github.com/ustclug/discussions/issues/294
  export CARGO_HTTP_MULTIPLEXING=false
fi

# Rime
if [[ "$OSTYPE" =~ 'linux-gnu' ]]; then
  export RIME_SHARED="/usr/share/rime-data"
  export RIME_USER="$HOME/.config/ibus/rime"
elif [[ "$OSTYPE" =~ 'darwin' ]]; then
  export RIME_SHARED="/Library/Input Methods/Squirrel.app/Contents/SharedSupport"
  export RIME_USER="$HOME/Library/Rime"
fi
export RIME="$RIME_USER"

# }

# Key bindings {

if [ -n "$ZSH_VERSION" ]; then
  # Mac USB keypad
  # 0 . Enter
  bindkey -s "^[Op" "0"
  bindkey -s "^[On" "."
  bindkey -s "^[OM" "^M"
  # 1 2 3
  bindkey -s "^[Oq" "1"
  bindkey -s "^[Or" "2"
  bindkey -s "^[Os" "3"
  # 4 5 6
  bindkey -s "^[Ot" "4"
  bindkey -s "^[Ou" "5"
  bindkey -s "^[Ov" "6"
  # 7 8 9
  bindkey -s "^[Ow" "7"
  bindkey -s "^[Ox" "8"
  bindkey -s "^[Oy" "9"
  # + -  * / =
  bindkey -s "^[Ok" "+"
  bindkey -s "^[Om" "-"
  bindkey -s "^[Oj" "*"
  bindkey -s "^[Oo" "/"
  bindkey -s "^[OX" "="
fi

# }

if [[ -z "$ZPREZTODIR" ]]; then
    source "$HOME/.exports-cli"
    source "$HOME/.exports-git"
fi

if [[ `hostname` =~ \\.corp\\.google\\.com ]]; then
  source $HOME/.exports-google
fi
