#!/bin/bash

# git-annex
alias gA='git annex'
alias gAa='git annex add'
alias gAc='git annex copy'
alias gAe='git annex export'
alias gAg='git annex get'
alias gAi='git annex info'
alias gAI='git annex import'
alias gAl='git annex list'
alias gAL='git annex lock'
alias gAm='git annex move'
alias gAs='git annex status'
alias gAu='git annex unlock'
alias gAx='git annex drop'
alias gAy='git annex sync'
alias gAz='git annex undo'
